server:
  port: 8080

spring:
  application:
    name: t1-java-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/t1_demo
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: localhost:9092
    session:
      timeout:
        ms: 15000

    consumer:
      group-id: t1-demo
      group-id-account: group-2
      group-id-transaction: group-3
      max:
        poll:
          records: 1
          interval:
            ms: 3000

    topic:
      client_registration: t1_demo_client_registration
      client_account: t1_demo_client_account
      client_transactions: t1_demo_client_transactions
      metric_trace: t1_demo_metric_trace
      error_trace: t1_demo_error_trace
      transaction-errors: t1_demo_client_transaction_errors

    listener:
      poll:
        timeout: 1000
    max:
     partition:
      fetch:
        bytes: 300000

  metric:
    execution:
      time: 10

security:
  token: eijveo849357vcuvn3490isdjfu09dfj309msdfgl433vdkfjne4343jn
  expiration: 86400000

integration:
  url: http://localhost:8088
  resource: /bsc-wire-mock/api/client/check
  retry-count: 3
  retry-backoff: 1000

logging:
  level:
    ROOT: INFO
    ru.t1.java.demo.controller.ClientController: DEBUG
